feat: serialize 3 new fields for assignments
openedx/enterprise-access pull request #292
Opened 2023-10-12 00:04 UTC by pwnage101

* actions: a list of all actions for the assignment.
* combined_status: intended to power the "Status" column in the frontend display.
* recent_action: intended to power the "Recent action" column in the frontend display.

ENT-7780

2023-10-17 01:35 UTC, pwnage101 commented on enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py
> +from django.db.models import Case, Exists, F, Max, OuterRef, Prefetch, Q, Value, When
I think this one line exemplifies my concerns over the last week about frontend-backend design compatibility and tech debt.  There's a time and place for ORM magic, this should not have been one of them.

2023-10-17 01:40 UTC, pwnage101 commented
Right now this doesn't give the frontend an direct field to distinguish between "Notifying" and "Waiting" assignments, but it is sorted correctly.  I'd like to address that in a separate PR tomorrow.

2023-10-18 14:12 UTC, iloveagent57 requested changes
(Experimenting with big red button)
This looks great! Two questions to maybe help with DB query count.

2023-10-18 14:12 UTC, iloveagent57 commented on enterprise_access/apps/api/serializers/content_assignments/assignment.py
> +        source='get_recent_action_data',
Couldn't these use the annotated fields you added to the queryset?  That would save a couple of queries per row of response data.

2023-10-18 14:12 UTC, iloveagent57 commented on enterprise_access/apps/api/v1/views/content_assignments/assignments_admin.py
> +        queryset = LearnerContentAssignment.objects.all()
Should we throw a `select_related('actions')` on here?

2023-10-18 14:36 UTC, iloveagent57 commented on enterprise_access/apps/api/serializers/content_assignments/assignment.py
> +        source='get_recent_action_data',
...or it's possible that an upstream `select_related()` would avoid the additional queries, and that using these functions as the source is fine.

2023-10-18 17:46 UTC, merged