feat: Added drf-spectacular package and settings
openedx/enterprise-access pull request #97
Opened 2023-01-24 14:39 UTC by zamanafzal

2023-01-27 06:08 UTC, saleem-latif requested changes

2023-01-27 06:08 UTC, saleem-latif commented on enterprise_access/settings/base.py
> +    'POSTPROCESSING_HOOKS': ['enterprise_access.oas.postprocess_schema_enums']
I can't find this file in the PR, I think you forgot to add to git.

2023-01-27 06:08 UTC, saleem-latif commented on enterprise_access/settings/base.py
> +    'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': False,
We do not need this setting, this setting is only useful for `drf_spectacular.hooks.postprocess_schema_enums` hook and we are not using that here.

2023-01-31 10:24 UTC, saleem-latif approved these changes

2023-01-31 10:24 UTC, saleem-latif commented on enterprise_access/apps/core/oas.py
> +    simple replacement of Enum/Choices that globally share the same name and have
I think we should update the doc string to reflect current behavior.

2023-01-31 15:44 UTC, johnnagro reviewed
Please close without merging. Thanks for putting this together. We discussed this in Scrum of Scrums this morning:

https://2u-internal.atlassian.net/wiki/spaces/SOL/pages/300580900/EMET+Scrum+of+Scrums+Notes#2023%2F01%2F31

The decision was that for now we do NOT recommend merging this. Please close without merging. We may come back to it later. For now we'd prefer making ENUM columns non-nullable. Please find @iloveagent57 or myself for further context.

2023-01-31 20:36 UTC, closed without merging